env:
    MANIFEST: # Manifest URL
    MANIFEST_BRANCH: # Manifest Branch (eg: ten)
    DEVICE: # Device Codename
    OEM: # Device OEM
    DT_LINK: # Link of the Device Tree
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: # Link of the Vendor Tree
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: # Link of the Kernel Source
    PLATFORM: # SoC Platform (eg: msm8916)
    KT_PATH: kernel/$OEM/$PLATFORM
    EXTRA_CMD: # Any Extra Command to Run Before Building
    LUNCH_COMBO: # Lunch Combo (eg: "lineage_${DEVICE}-userdebug")
    TARGET: # Build Target (eg: bacon)
    OUTPUT: # File to Upload (eg: "lineage*.zip")

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

task:
  name: "AOSP Build"
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
