env:
    MANIFEST: https://github.com/The-RAVEN-OS/manifest.git
    MANIFEST_BRANCH: twelve
    DEVICE: WSP_sprout
    OEM: hmd
    DT_LINK: https://github.com/SmallPP420/final_device_WSP_sprout.git -b lineage-18
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/SmallPP420/vendor_nokia_WSP_sprout -b lineage-18
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/jro1979oliver/android_kernel_lenovo_msm8916.git
    PLATFORM: msm8916
    KT_PATH: kernel/$OEM/$PLATFORM
    EXTRA_CMD: "git clone --depth=1 https://github.com/ghostrider-reborn/prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-6.x.git $SYNC_PATH/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-6.x"
    LUNCH_COMBO: WSP_sprout-userdebug
    TARGET: bacon
    OUTPUT: RROS*.zip

    # Not Recommended to Change
    SYNC_PATH: $HOME/work # Do NOT use "~". Use $HOME instead.
    CCACHE_SIZE: 30G
    CCACHE_DIR: $HOME/work/.ccache
    J_VAL: 16

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "AOSP Build"
  trigger_type: manual
  timeout_in: 120m
  container:
      image: registry.gitlab.com/sushrut1101/docker:latest
      cpu: 8
      memory: 32G

  Sync_script:
      - bash sync.sh

  Build_script:
      - bash build.sh
     
  Upload_script:
      - export TIMEOUT=43200 # Download Link Timeout (in Minutes)
      - bash upload.sh
